APP_TARGET="storage_node_app"
NODE_ID="store-1"
LISTEN="127.0.0.1:9501"
DATA_DIR="data"
LOG_FILE="logs/store-1.log"
PID_FILE="pids/store-1.pid"
CONFIG_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-1/config.json"
CLUSTER_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-1/cluster.json"
RAFT_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-1/raft.json"
STORE_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-1/store.json"
VIEW_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-1/view.json"
