APP_TARGET="storage_node_app"
NODE_ID="store-6"
LISTEN="127.0.0.1:9506"
DATA_DIR="data"
LOG_FILE="logs/store-6.log"
PID_FILE="pids/store-6.pid"
CONFIG_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-6/config.json"
CLUSTER_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-6/cluster.json"
RAFT_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-6/raft.json"
STORE_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-6/store.json"
VIEW_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-6/view.json"
