APP_TARGET="view_node_app"
NODE_ID="view-2"
LISTEN="127.0.0.1:9302"
DATA_DIR="data"
LOG_FILE="logs/view-2.log"
PID_FILE="pids/view-2.pid"
CONFIG_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/view-2/config.json"
CLUSTER_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/view-2/cluster.json"
RAFT_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/view-2/raft.json"
STORE_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/view-2/store.json"
VIEW_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/view-2/view.json"
