APP_TARGET="storage_node_app"
NODE_ID="store-5"
LISTEN="127.0.0.1:9505"
DATA_DIR="data"
LOG_FILE="logs/store-5.log"
PID_FILE="pids/store-5.pid"
CONFIG_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-5/config.json"
CLUSTER_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-5/cluster.json"
RAFT_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-5/raft.json"
STORE_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-5/store.json"
VIEW_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-5/view.json"
