APP_TARGET="storage_node_app"
NODE_ID="store-4"
LISTEN="127.0.0.1:9504"
DATA_DIR="data"
LOG_FILE="logs/store-4.log"
PID_FILE="pids/store-4.pid"
CONFIG_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-4/config.json"
CLUSTER_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-4/cluster.json"
RAFT_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-4/raft.json"
STORE_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-4/store.json"
VIEW_SECTION_PATH="/home/yangjilei/Code/C++/CQUPT_Raft/real_examples/object-storage-local-011-node-self-contained/nodes/store-4/view.json"
